# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {C:/Users/FranticUser/Desktop/fpga stuff/Linear Feedback Shift Register/Linear Feedback Shift Register.cache/wt} [current_project]
set_property parent.project_path {C:/Users/FranticUser/Desktop/fpga stuff/Linear Feedback Shift Register/Linear Feedback Shift Register.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib {
  {C:/Users/FranticUser/Desktop/fpga stuff/Linear Feedback Shift Register/Linear Feedback Shift Register.srcs/sources_1/new/LSFR.v}
  {C:/Users/FranticUser/Desktop/fpga stuff/Linear Feedback Shift Register/Linear Feedback Shift Register.srcs/sources_1/new/Transmitter.v}
  {C:/Users/FranticUser/Desktop/fpga stuff/Linear Feedback Shift Register/Linear Feedback Shift Register.srcs/sources_1/new/Db.v}
  {C:/Users/FranticUser/Desktop/fpga stuff/Linear Feedback Shift Register/Linear Feedback Shift Register.srcs/sources_1/new/Top.v}
}
read_xdc {{C:/Users/FranticUser/Desktop/fpga stuff/Linear Feedback Shift Register/ELEV-BASYS3.xdc}}
set_property used_in_implementation false [get_files {{C:/Users/FranticUser/Desktop/fpga stuff/Linear Feedback Shift Register/ELEV-BASYS3.xdc}}]

synth_design -top top -part xc7a35tcpg236-1
write_checkpoint -noxdef top.dcp
catch { report_utilization -file top_utilization_synth.rpt -pb top_utilization_synth.pb }
